name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - name: Fetch Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Check if PR is ready for auto-merge
      id: check-merge
      run: |
        echo "Auto-merge conditions:"
        echo "- Actor: ${{ github.actor }}"
        echo "- Update type: ${{ steps.metadata.outputs.update-type }}"
        echo "- Dependency type: ${{ steps.metadata.outputs.dependency-type }}"
        echo "- Package ecosystem: ${{ steps.metadata.outputs.package-ecosystem }}"
        
        # Define auto-merge conditions
        AUTO_MERGE=false
        
        # Auto-merge patch updates for all dependencies
        if [[ "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-patch" ]]; then
          AUTO_MERGE=true
          echo "✅ Patch update - auto-merge enabled"
        fi
        
        # Auto-merge minor updates for development dependencies
        if [[ "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-minor" && "${{ steps.metadata.outputs.dependency-type }}" == "direct:development" ]]; then
          AUTO_MERGE=true
          echo "✅ Minor dev dependency update - auto-merge enabled"
        fi
        
        # Auto-merge GitHub Actions updates (they're usually safe)
        if [[ "${{ steps.metadata.outputs.package-ecosystem }}" == "github_actions" ]]; then
          AUTO_MERGE=true
          echo "✅ GitHub Actions update - auto-merge enabled"
        fi
        
        # Special cases for trusted dependencies with minor updates
        TRUSTED_DEPS="tokio async-trait futures serde chrono uuid thiserror tracing"
        for dep in $TRUSTED_DEPS; do
          if [[ "${{ steps.metadata.outputs.dependency-names }}" == *"$dep"* && "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-minor" ]]; then
            AUTO_MERGE=true
            echo "✅ Trusted dependency $dep minor update - auto-merge enabled"
            break
          fi
        done
        
        echo "auto_merge=$AUTO_MERGE" >> $GITHUB_OUTPUT
        
        if [[ "$AUTO_MERGE" == "true" ]]; then
          echo "🤖 This PR qualifies for auto-merge"
        else
          echo "⏸️ This PR requires manual review"
        fi

    - name: Wait for CI to complete
      if: steps.check-merge.outputs.auto_merge == 'true'
      uses: fountainhead/action-wait-for-check@v1.2.0
      id: wait-for-ci
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: "Test Suite"
        ref: ${{ github.event.pull_request.head.sha }}
        timeoutSeconds: 1800  # 30 minutes
        intervalSeconds: 30

    - name: Check CI status
      if: steps.check-merge.outputs.auto_merge == 'true'
      run: |
        if [[ "${{ steps.wait-for-ci.outputs.conclusion }}" == "success" ]]; then
          echo "✅ CI passed - proceeding with auto-merge"
        else
          echo "❌ CI failed - will not auto-merge"
          exit 1
        fi

    - name: Enable auto-merge for Dependabot PRs
      if: steps.check-merge.outputs.auto_merge == 'true'
      run: |
        gh pr merge --auto --squash "$PR_URL"
        echo "🤖 Auto-merge enabled for PR"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment on manual review needed
      if: steps.check-merge.outputs.auto_merge == 'false'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🔍 **Manual Review Required**
            
            This Dependabot PR requires manual review because:
            - Update type: ${{ steps.metadata.outputs.update-type }}
            - Dependency type: ${{ steps.metadata.outputs.dependency-type }}
            - Package ecosystem: ${{ steps.metadata.outputs.package-ecosystem }}
            
            Please review the changes and merge manually if appropriate.
            
            **Auto-merge criteria:**
            - ✅ Patch updates (any dependency)
            - ✅ Minor updates (development dependencies only)
            - ✅ GitHub Actions updates
            - ✅ Minor updates for trusted dependencies (tokio, serde, etc.)
            `
          })

  security-check:
    name: Security Check for Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-audit
      uses: taiki-e/install-action@cargo-audit

    - name: Run security audit
      run: |
        if cargo audit; then
          echo "✅ No security vulnerabilities found"
        else
          echo "❌ Security vulnerabilities detected in dependencies"
          echo "This PR introduces security issues and should not be auto-merged"
          exit 1
        fi

    - name: Comment on security issues
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚨 **Security Issues Detected**
            
            This Dependabot PR introduces security vulnerabilities and has been blocked from auto-merge.
            
            Please review the security audit output above and address any issues before merging.
            
            Run \`cargo audit\` locally to see detailed vulnerability information.
            `
          })